--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-23-2022   
--------------------------------------------------------
--DocumentType
INSERT INTO DOCUMENT_TYPE (NAME,CREATIONDATE,UPDATEDATE,ACTIVE) VALUES ('Cedula de ciudadania',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO DOCUMENT_TYPE (NAME,CREATIONDATE,UPDATEDATE,ACTIVE) VALUES ('Cedula de extranjeria',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO DOCUMENT_TYPE (NAME,CREATIONDATE,UPDATEDATE,ACTIVE) VALUES ('Pasaporte',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO DOCUMENT_TYPE (NAME,CREATIONDATE,UPDATEDATE,ACTIVE) VALUES ('Registro civil',CURRENT_DATE,CURRENT_DATE,1);

---Category
Insert into CATEGORY (NAME, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Datos basicos',CURRENT_DATE,CURRENT_DATE,1);
Insert into CATEGORY (NAME, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Datos educativos',CURRENT_DATE,CURRENT_DATE,1);          
Insert into CATEGORY (NAME, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Datos geograficos',CURRENT_DATE,CURRENT_DATE,1);
Insert into CATEGORY (NAME, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Datos culturales',CURRENT_DATE,CURRENT_DATE,1);
Insert into CATEGORY (NAME, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Resultados prueba saber',CURRENT_DATE,CURRENT_DATE,1);

---Question                                                             
Insert into QUESTION (NAME, DESCRIPTION, CATEGORY, CREATIONDATE,UPDATEDATE,ACTIVE) values ('gender','Elija su género',1,CURRENT_DATE,CURRENT_DATE,1);
Insert into QUESTION (NAME, DESCRIPTION, CATEGORY, CREATIONDATE,UPDATEDATE,ACTIVE) values ('age','Elija su fecha de nacimiento',1,CURRENT_DATE,CURRENT_DATE,1);          
Insert into QUESTION (NAME, DESCRIPTION, CATEGORY, CREATIONDATE,UPDATEDATE,ACTIVE) values ('gradeAverage','Digite su promedio en calificaciones de su último ciclo escolar culminado.',2,CURRENT_DATE,CURRENT_DATE,1);
Insert into QUESTION (NAME, DESCRIPTION, CATEGORY, CREATIONDATE,UPDATEDATE,ACTIVE) values ('educationLevel','Seleccione su nivel educativo',2,CURRENT_DATE,CURRENT_DATE,1);
Insert into QUESTION (NAME, DESCRIPTION, CATEGORY, CREATIONDATE,UPDATEDATE,ACTIVE) values ('city','Elija su ciudad de interés',3,CURRENT_DATE,CURRENT_DATE,1);
Insert into QUESTION (NAME, DESCRIPTION, CATEGORY, CREATIONDATE,UPDATEDATE,ACTIVE) values ('ethnicGroup','Elija su grupo etnico',4,CURRENT_DATE,CURRENT_DATE,1);
Insert into QUESTION (NAME, DESCRIPTION, CATEGORY, CREATIONDATE,UPDATEDATE,ACTIVE) values ('resultPruebaSaber','Elija el rango de su resultado en pruebas saber',5,CURRENT_DATE,CURRENT_DATE,1);

---Answer
--- Gender: male & female
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Hombre',1,'Género masculino',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Mujer',1,'Género femenino',CURRENT_DATE,CURRENT_DATE,1);


---Age
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('0-10',2,'Edad entre 0-10 años.',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('10-18',2,'Edad entre 10-18 años.',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('18-23',2,'Edad entre 18-23 años.',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('23-30',2,'Edad entre 23-30 años.',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('30-40',2,'Edad entre 30-40 años.',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('40-50',2,'Edad entre 40-50 años.',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('50-60',2,'Edad entre 50-60 años-',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('60-70',2,'Edad entre 60-70 años.',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('70-80',2,'Edad entre 70-80 años.',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('80-90',2,'Edad entre 80-90 años.',CURRENT_DATE,CURRENT_DATE,1);



--- gradeAverage
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('0 - 2.0',3,'Promedio entre 0 y 2.0',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('2.0 - 3.0',3,'Promedio entre 2.0 y 3.0',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('3.0 - 3.5',3,'Promedio entre 3.0 y 3.5',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('3.5 - 4.0',3,'Promedio entre 3.5 y 4.0',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('4.0 - 4.5',3,'Promedio entre 4.0 y 4.5',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('4.5 - 5.0',3,'Promedio entre 4.5 y 5.0',CURRENT_DATE,CURRENT_DATE,1);

--- education level: primaria, bachillerato, preparatoria, tecnico, tecnologo, profesional
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Primaria',4, 'Máximo grado escolar alcanzado fue primaria (5°)',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Secundaria',4, 'Máximo grado escolar alcanzado fue secundaria (9°)',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Bachillerato',4, 'Máximo grado escolar alcanzado 11°',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Tecnico',4, 'Máximo grado escolar alcanzado fue técnico',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Tecnólogo',4, 'Máximo grado escolar alcanzado fue tecnólogo',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Profesional - pregrado',4, 'Máximo grado escolar alcanzado fue pregrado',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Maestría',4, 'Máximo grado escolar alcanzado fue maestría',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Doctorado',4, 'Máximo grado escolar alcanzado fue doctorado',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Pos-doctorado',4, 'Máximo grado escolar alcanzado fue pos-doctorado',CURRENT_DATE,CURRENT_DATE,1);


-- ciudad
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Bogotá',5, 'Bogotá D.C.',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Medellin',5, 'Bogotá D.C.',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Cali',5, 'Bogotá D.C.',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Tunja',5, 'Bogotá D.C.',CURRENT_DATE,CURRENT_DATE,1);


-- ethnicGroup
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Negro',6, 'Comunidades Negras',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Afrocolombiano',6, 'Comunidades Afrocolombianas',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('NARP',6, 'Raizales y Palenqueras- NARP',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Indígena',6, 'Pueblos Indígenas',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Gitano',6, 'Pueblo Rrom o Gitano',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Ninguno',6, 'No pertenece a ningun grupo étnico previamente mencionado',CURRENT_DATE,CURRENT_DATE,1);

---pruebaSaber

Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('0-100',7,'Resultado total entre 0-100 puntos',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('100-200',7,'Resultado total entre 100-200 puntos',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('200-250',7,'Resultado total entre 200-250 puntos',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('250-300',7,'Resultado total entre 250-300 puntos',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('300-350',7,'Resultado total entre 300-350 puntos',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('350-400',7,'Resultado total entre 350-400 puntos',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('400-450',7,'Resultado total entre 400-450 puntos',CURRENT_DATE,CURRENT_DATE,1);
Insert into ANSWER (NAME, QUESTION, DESCRIPTION, CREATIONDATE,UPDATEDATE,ACTIVE) values ('450-500',7,'Resultado total entre 450-500 puntos',CURRENT_DATE,CURRENT_DATE,1);



---Candidates
Insert into CANDIDATE (NAME,SURNAME,BIRTHDAY,DOCUMENTNUMBER,DOCUMENTTYPE,EMAIL, CREATIONDATE,UPDATEDATE,ACTIVE) values ('Francisco','Rojas',DATE '1983-10-01',102312312,1,'francisRojas@gmail.com',CURRENT_DATE,CURRENT_DATE,1);

--- UserInformation
INSERT INTO USER_INFORMATION (ANSWER,CANDIDATE ,CREATIONDATE,UPDATEDATE,ACTIVE) VALUES (1,1,CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO USER_INFORMATION (ANSWER,CANDIDATE ,CREATIONDATE,UPDATEDATE,ACTIVE) VALUES (5,1,CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO USER_INFORMATION (ANSWER,CANDIDATE ,CREATIONDATE,UPDATEDATE,ACTIVE) VALUES (12,1,CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO USER_INFORMATION (ANSWER,CANDIDATE ,CREATIONDATE,UPDATEDATE,ACTIVE) VALUES (20,1,CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO USER_INFORMATION (ANSWER,CANDIDATE ,CREATIONDATE,UPDATEDATE,ACTIVE) VALUES (25,1,CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO USER_INFORMATION (ANSWER,CANDIDATE ,CREATIONDATE,UPDATEDATE,ACTIVE) VALUES (31,1,CURRENT_DATE,CURRENT_DATE,1);