
CREATE TABLE CANDIDATE (
    id NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 NOT NULL ,
    name VARCHAR2(100) NOT NULL,
    surname VARCHAR2(100) NOT NULL,
    birthday DATE NOT NULL,
    documentNumber VARCHAR2(20) UNIQUE NOT NULL,
    documentType NUMBER NOT NULL,
    email VARCHAR2(100) NOT NULL,
    creationDate DATE,
    updateDate DATE,
	deleteDate DATE,
	active SMALLINT NOT NULL,
    CONSTRAINT CANDIDATE_PK PRIMARY KEY (id) USING INDEX 
  (
      CREATE UNIQUE INDEX CANDIDATE_PK ON CANDIDATE (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
);



CREATE TABLE CONVOCATION (
    id NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1  NOT NULL,
    name VARCHAR(255) NOT NULL,
    dateConvocation DATE NOT NULL,
    CONSTRAINT CONVOCATION_PK PRIMARY KEY (id) USING INDEX 
  (
      CREATE UNIQUE INDEX CONVOCATION_PK ON CONVOCATION (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
);

CREATE TABLE REPORT (
    id NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1  NOT NULL ,
    candidateName VARCHAR(255) NOT NULL,
    candidateId NUMBER NOT NULL,
    totalScore NUMBER NOT NULL,
    convocation NUMBER NOT NULL,
    CONSTRAINT REPORT_PK PRIMARY KEY (id) USING INDEX 
  (
      CREATE UNIQUE INDEX REPORT_PK ON REPORT (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
);

CREATE TABLE REPORTDETAIL (
    id NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1  NOT NULL ,
    feature VARCHAR(255) NOT NULL,
    answer VARCHAR(255) NOT NULL,
    score NUMBER NOT NULL,
    reportFk NUMBER NOT NULL,
    CONSTRAINT REPORTDETAIL_PK PRIMARY KEY (id) USING INDEX 
  (
      CREATE UNIQUE INDEX REPORTDETAIL_PK ON REPORTDETAIL (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
);

CREATE TABLE CANDIDATE_CONVOCATION (
    id NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 NOT NULL,
    candidate_Id NUMBER NOT NULL,
    convocation_Id NUMBER NOT NULL,
    CONSTRAINT CANDIDATE_CONVOCATION_PK PRIMARY KEY (id) USING INDEX 
  (
      CREATE UNIQUE INDEX CANDIDATE_CONVOCATION_PK ON CANDIDATE_CONVOCATION (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
);

CREATE TABLE FEATURE (
    id NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1  NOT NULL,
    name VARCHAR(255) NOT NULL,
    convocation NUMBER NOT NULL,
    weight NUMBER NOT NULL,
    CONSTRAINT FEATURE_PK PRIMARY KEY (id) USING INDEX 
  (
      CREATE UNIQUE INDEX FEATURE_PK ON FEATURE (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
);

CREATE TABLE PRIORITY (
    id NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1  NOT NULL,
    name VARCHAR(255) NOT NULL,
    value NUMBER NOT NULL,
    feature NUMBER NOT NULL,
    CONSTRAINT PRIORIY_PK PRIMARY KEY (id) USING INDEX 
  (
      CREATE UNIQUE INDEX PRIORIY_PK ON PRIORITY (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
);

CREATE TABLE DOCUMENT_TYPE (
    id NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 NOT NULL,
    name VARCHAR(255) NOT NULL,
    creationDate DATE NOT NULL,
    updateDate DATE NOT NULL,
	deleteDate DATE,
	active SMALLINT NOT NULL,
    CONSTRAINT DOCUMENT_TYPE_PK PRIMARY KEY (id) USING INDEX 
  (
      CREATE UNIQUE INDEX DOCUMENT_TYPE_PK ON DOCUMENT_TYPE (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
);

CREATE TABLE ANSWER (
    id NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 NOT NULL,
    name VARCHAR(255) NOT NULL,
    question NUMBER NOT NULL,
    description VARCHAR(255) NOT NULL,
    creationDate DATE NOT NULL,
    updateDate DATE NOT NULL,
	deleteDate DATE,
	active SMALLINT NOT NULL,
    CONSTRAINT ANSWER_PK PRIMARY KEY (id) USING INDEX 
  (
      CREATE UNIQUE INDEX ANSWER_PK ON ANSWER (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
);

CREATE TABLE CATEGORY (
    id NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 NOT NULL,
    name VARCHAR(255) NOT NULL,
    creationDate DATE NOT NULL,
    updateDate DATE NOT NULL,
	deleteDate DATE,
	active SMALLINT NOT NULL,
    CONSTRAINT CATEGORY_PK PRIMARY KEY (id) USING INDEX 
  (
      CREATE UNIQUE INDEX CATEGORY_PK ON CATEGORY (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
);

CREATE TABLE USER_INFORMATION (
    id NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 NOT NULL,
    answer NUMBER NOT NULL,
    candidate NUMBER NOT NULL,
    creationDate DATE NOT NULL,
    updateDate DATE NOT NULL,
	deleteDate DATE,
	active SMALLINT NOT NULL,
    CONSTRAINT USER_INFORMATION_PK PRIMARY KEY (id) USING INDEX 
  (
      CREATE UNIQUE INDEX USER_INFORMATION_PK ON USER_INFORMATION (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
);

CREATE TABLE QUESTION (
    id NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    category NUMBER NOT NULL,
    creationDate DATE NOT NULL,
    updateDate DATE NOT NULL,
	deleteDate DATE,
	active SMALLINT NOT NULL,
    CONSTRAINT QUESTION_PK PRIMARY KEY (id) USING INDEX 
  (
      CREATE UNIQUE INDEX QUESTION_PK ON QUESTION (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
);


-- Foreign keys
ALTER TABLE CANDIDATE ADD FOREIGN KEY (documentType) REFERENCES DOCUMENT_TYPE(id);
ALTER TABLE REPORT ADD FOREIGN KEY (convocation) REFERENCES convocation(id);
ALTER TABLE FEATURE ADD FOREIGN KEY (convocation) REFERENCES convocation(id);
ALTER TABLE PRIORITY ADD FOREIGN KEY (feature) REFERENCES feature(id);
ALTER TABLE ANSWER ADD FOREIGN KEY (question) REFERENCES question(id);
ALTER TABLE USER_INFORMATION ADD FOREIGN KEY (candidate) REFERENCES candidate(id);
ALTER TABLE USER_INFORMATION ADD FOREIGN KEY (answer) REFERENCES answer(id);
ALTER TABLE QUESTION ADD FOREIGN KEY (category) REFERENCES category(id);
ALTER TABLE CANDIDATE_CONVOCATION ADD FOREIGN KEY (CANDIDATE_ID) REFERENCES candidate(id);
ALTER TABLE CANDIDATE_CONVOCATION ADD FOREIGN KEY (CONVOCATION_ID) REFERENCES convocation(id);
ALTER TABLE REPORTDETAIL  ADD FOREIGN KEY (REPORTFK) REFERENCES REPORT(id);
